#!/usr/bin/env bash
# The script displays "Best School" 10 times, then say 'Hi' on a new line
i=1
while [ $i -le 10 ]; do
  if [ $i -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else 
    echo "Best School"
  fi
  i=$((i + 1))
done
