#!/usr/bin/env bash
# The script will loop from 1 to 10, then displays different message for spefic iterations
i=1
while [ $i -le 10 ]; do 
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
