#!/usr/bin/env bash
# Check if the file  exist 
if [ -e "school" ]; then
     echo "school file exist"
     # Check if he file empty
     if [ ! -s "school" ]; then
	     echo "school file is empty"
     else
	     echo "school file is not empty"
     fi

     # Check if the file is regular file 
     if [ -f "school" ]; then 
	     echo "school is a regular file"
     fi
else
	echo "school file does not exist"
fi
